services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=msgdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
  cmserviceapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/msgdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
volumes:
  pgdata: {}