spring:
  application:
    name: cm-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: postgres

jwt:
  key: YzEyMzR0bXZxQzRmNTZ2cEFoUGVpMWdIajU3aWdoZ2g

server:
  address: 0.0.0.0